language: go

go:
- 1.11.x

env:
- GO111MODULE=on

before_install:
  # gox simplifies building for multiple architectures
  - go get golang.org/x/lint/golint
  - go get github.com/mitchellh/gox

install:
  # skip

script:
  - make deps
  - make test
  - make deploy

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "${GITHUB_OAUTH_TOKEN_SECURE}"
  file: bin/*
  on:
    repo: deps-cloud/dis
    tags: true
